pipeline:
  name: Java 17
  identifier: Java_17
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1715105217041
        repoName: <+input>
        build: <+input>
        depth: 1
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    connectorRef: AWS_Personal
                    image: 295439051676.dkr.ecr.sa-east-1.amazonaws.com/build-images:jdk17
                    shell: Sh
                    command: |-
                      ## mvn clean package dependency:copy-dependencies
                      projectName=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.name}' --non-recursive exec:exec)
                      projectVersion=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
                    outputVariables:
                      - name: projectName
                      - name: projectVersion
                    imagePullPolicy: Always
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      echo <+stage.variables.projectName>
                      echo <+stage.variables.projectVersion>
        variables:
          - name: projectName
            type: String
            description: ""
            required: false
            value: <+input>
          - name: projectVersion
            type: String
            description: ""
            required: false
            value: <+input>
  allowStageExecutions: false
