pipeline:
  name: Java 17
  identifier: Java_17
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1715105217041
        repoName: <+input>
        build: <+input>
        depth: 1
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: get project info
                  identifier: get_project_info
                  spec:
                    connectorRef: AWS_Personal
                    image: 295439051676.dkr.ecr.sa-east-1.amazonaws.com/build-images:jdk17
                    shell: Sh
                    command: |-
                      projectName=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.name}' --non-recursive exec:exec)
                      projectVersion=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
                    outputVariables:
                      - name: projectName
                      - name: projectVersion
                    imagePullPolicy: Always
          sharedPaths:
            - /root/.m2
          caching:
            enabled: false
            paths:
              - /root/.m2
        variables:
          - name: projectName
            type: String
            description: ""
            required: false
            value: <+input>
          - name: projectVersion
            type: String
            description: ""
            required: false
            value: <+input>
    - stage:
        name: teste
        identifier: teste
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      echo <+pipeline.variables.projectName>
                      echo <+pipeline.variables.projectVersion>
  allowStageExecutions: false
  variables:
    - name: projectName
      type: String
      description: ""
      required: false
      value: <+pipeline.stages.Build.variables.projectName>
    - name: projectVersion
      type: String
      description: ""
      required: false
      value: <+pipeline.stages.Build.variables.projectVersion>
