pipeline:
  name: Java 17
  identifier: Java_17
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1715105217041
        repoName: <+input>
        build: <+input>
        depth: 1
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    connectorRef: AWS_Personal
                    image: 295439051676.dkr.ecr.sa-east-1.amazonaws.com/build-images:jdk17
                    shell: Sh
                    command: |-
                      mvn clean package dependency:copy-dependencies
                      projectName=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.name}' --non-recursive exec:exec)
                      projectVersion=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
                    outputVariables:
                      - name: projectName
                      - name: projectVersion
                    imagePullPolicy: Always
              - step:
                  name: Sonarqube Analysis
                  identifier: Sonarqube_Analysis
                  template:
                    templateRef: Sonarqube_Java_17
                    versionLabel: "1.0"
              - step:
                  type: S3Upload
                  name: upload JAR to S3
                  identifier: upload_JAR_to_S3
                  spec:
                    connectorRef: AWS_Personal
                    region: sa-east-1
                    bucket: <+stage.variables.projectName>-artifactory
                    sourcePath: target/<+stage.variables.projectName>-<+stage.variables.projectVersion>.jar
                    target: /
              - step:
                  type: BuildAndPushECR
                  name: Build and Push to ECR
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: AWS_Personal
                    region: sa-east-1
                    account: <+secrets.getValue("AWSAccountID")>
                    imageName: <+stage.variables.projectName>
                    tags:
                      - <+stage.variables.projectVersion>
        variables:
          - name: projectName
            type: String
            description: ""
            required: false
            value: <+input>
          - name: projectVersion
            type: String
            description: ""
            required: false
            value: <+input>
  allowStageExecutions: false
